### PR TITLE
Provide retry options for Redis cache reads and inserts

### LINKED ISSUE #361: Provide an option to retry a failed cache insert.
### Feature description

I would like to be able to retry `reading from` and `writing into` Redis, when the connection to redis is lost.

Our current problem is the following:
```java
@Cacheable // (1) InterceptPhase = -100
@Retryable // (2) InterceptPhase = -60
public String getValue(String someParameter){
 // calling remote service that can fail (3)
  return "value"
}
(4)
```
Explaination:
1. `@Cacheable` checks if this method with the given parameter is in our Cache (Redis) If it is found, the cache hit will return immediatly our desired value. This interceptor kicks in first, since its intercept Phase is lower than `@Retryable` 
2. `@Retryable` will retry in case of failures of computing our desired value (i.e. calls a remote service). For simplicity reasons it just shall retry on any problem.
3. Calling a remote service that fails is covered by retryable
4. When this method return as value `@Cacheable` will store the result within our cache. Unfortunatly this cache is a remote service, which can also fail. We could see a few `Connection reset` issues. 

Problem  / Feature 1: Reading from Redis can fail and should be retried
Problem / Feature 2: Writing into Redis can fail and should be retried

Having this scenario, i would love to see something like
```yml
micronaut:
   redis:
      retry: 
        read: 2 # Retry twice on failure
        insert: 2 # This triggers insert retry 
``` 

The given example solution is just for inspiration purposes!

While this scenario is pretty straight forward, we can run into some issues:
1. Failing inside of that method is 

Our

### PR DESCRIPTION
**Pull request by graemerocher**
## Summary
- add configurable retry counts for Redis cache reads and inserts
- apply retry handling to sync and async cache operations for both direct and pooled connections
- document the new configuration and add focused retry coverage

## Verification
- ./gradlew :micronaut-redis-lettuce:test --tests io.micronaut.configuration.lettuce.cache.AbstractRedisCacheSpec --tests io.micronaut.configuration.lettuce.cache.RedisCacheRetrySpec --rerun-tasks
- ./gradlew spotlessCheck

Resolves #361

### CODE REVIEW

**Comment by graemerocher** [comment]
@copilot apply changes based on the comments in [this thread](https://github.com/micronaut-projects/micronaut-redis/pull/745#pullrequestreview-4107064564)

File: redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/cache/AbstractRedisCacheConfiguration.java [hunk 1]
```diff
@@ -158,4 +160,42 @@ public Optional<Long> getInvalidateScanCount() {
     public void setInvalidateScanCount(@NonNull Long invalidateScanCount) {
         this.invalidateScanCount = invalidateScanCount;
     }
+
+    /**
+     * @return The number of times a failed cache read should be retried.
+     * @since 6.8.0
```
Comment (radovanradic) [inline redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/cache/AbstractRedisCacheConfiguration.java]: Should be since 7.0.0 (for other methods as well)

**Review by radovanradic — APPROVED** [review]

**Comment by graemerocher** [comment]
@copilot resolve the merge conflicts in this pull request
