### PR TITLE
Pass seconds to methods which receive seconds not milliseconds

### LINKED ISSUE #474: Redis Lettuce Expiration Set Incorrectly
### Expected Behavior

If I set the expire-after-write and expire-after-access

```yaml
redis:
  caches:
    accounts:
      expire-after-access: 24h
      expire-after-write: 24h
```

I expect the Redis TTL to be set at 24 hours, or 86400 seconds.

### Actual Behaviour

The cache TTL value is being set to 86400000 seconds, which is 1000 times the intended amount.

I discovered this after noticing via Redis Insight that the TTL was showing as over 2 years.
Screenshot 2024-01-10 at 10 19 28 AM

I then enabled trace logging on my project, and realized that the value coming back was 86400000 instead of the intended 86400 seconds. Here was the logging output:
```
$6
EXPIRE
$8
86400000
```

It seems to be a problem with converting the value of expireAfterAccess to milliseconds via the `Duration::toMillis` mapping. An example is found here in `AbstractRedisCache.java`:
```
this.expireAfterAccess = redisCacheConfiguration
.getExpireAfterAccess()
.map(Duration::toMillis)
.orElse(defaultRedisCacheConfiguration.getExpireAfterAccess().map(Duration::toMillis).orElse(null));
```
It seems the value of `expireAfterAccess` is still being treated as seconds instead of the expected milliseconds.

### Steps To Reproduce

1. Set the `expire-after-access` and `expire-after-write` within `application.yml` to `24h`.
2. Run the project.
3. Check your cache on a Redis client (such as Redis Insight)
4. Inspect the Time To Live value.

### Environment Information

JDK Version 17

### Example Application

_No response_

### Version

4.2.0

### PR DESCRIPTION
**Pull request by sdelamo**
Close: https://github.com/micronaut-projects/micronaut-redis/issues/474

`RedisAsynCommand::expire` methods takes seconds but we were passing milliseconds. 

There are other methods in the Redis API, for example the `RedisAsynCommand::pexpire` which takes milliseconds. Our tests, were hitting that method. That it is the reason why they were passing. 

This PR converts from milliseconds to seconds the methods that require seconds and it adds tests for those code paths.

### CODE REVIEW

File: redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/cache/RedisCache.java [hunk 1]
```diff
@@ -223,7 +223,8 @@ public <T> CompletableFuture<T> get(Object key, Argument<T> requiredType, Suppli
                     Optional<T> deserialized = valueSerializer.deserialize(data, requiredType);
                     boolean hasValue = deserialized.isPresent();
                     if (expireAfterAccess != null && hasValue) {
-                        return redisKeyAsyncCommands.expire(serializedKey, expireAfterAccess).thenApply(ignore -> deserialized.get());
+                        final long expireAfterAccessInSeconds = expireAfterAccess / 1000;
+                        return redisKeyAsyncCommands.expire(serializedKey, expireAfterAccessInSeconds).thenApply(ignore -> deserialized.get());
```
Comment (Mike-Svendsen-IL) [inline redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/cache/RedisCache.java]: Instead of converting to milliseconds (which could lose precision), maybe just use `pexpire`? (https://redis.io/docs/latest/commands/pexpire/)

Update - or I guess you mention something about `pexpire` in the PR description, but it isn't clear to me why not to use it here instead.

Comment (ChaimaaeROUAI) [reply redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/cache/RedisCache.java]: indeed , using pexpire would solve the issue rather than converting to milliseconds, I've added tests that hit the methods .
