### PR TITLE
Fix redis.timeout when redis.uri is configured

### LINKED ISSUE #649: The `redis.timeout` setting has no effect
### Expected Behavior

If I set `redis.timeout` then all operations should have that timeout

### Actual Behaviour

The default 1m timeout is still in effect

### Steps To Reproduce

1. Set a `redis.timeout` value, for example 1s
2. Observe that RedisCache.getNativeCache().getTimeout() still returns 1m

### Environment Information

_No response_

### Example Application

_No response_

### Version

4.7

### PR DESCRIPTION
**Pull request by graemerocher**
## Summary
- preserve separately bound RedisURI properties when `redis.uri`, `redis.uris`, or `redis.replica-uris` are used
- add a regression test covering timeout propagation to the created Lettuce client without requiring Docker

## Verification
- `./gradlew :micronaut-redis-lettuce:test --tests "*RedisConfigurationSpec"`
- `./gradlew :micronaut-redis-lettuce:spotlessCheck`

Resolves #649

### CODE REVIEW

**Comment by graemerocher** [comment]
@copilot apply changes based on the comments in [this thread](https://github.com/micronaut-projects/micronaut-redis/pull/740#pullrequestreview-4098797354)

File: redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/RedisConfigurationWithUriSettings.java [hunk 1]
```diff
@@ -0,0 +1,143 @@
...
+        new AtomicReference<>(ConfiguredRedisUriSettings.EMPTY);
+
+    @Override
+    public Optional<RedisURI> getUri() {
+        return super.getUri().map(this::applyConfiguredRedisUriSettings);
+    }
+
+    @Override
+    public List<RedisURI> getUris() {
+        return super.getUris().stream().map(this::applyConfiguredRedisUriSettings).collect(Collectors.toList());
```
Comment (sdelamo) [inline redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/RedisConfigurationWithUriSettings.java]:
```suggestion
        return super.getUris().stream().map(this::applyConfiguredRedisUriSettings).toList();
```

File: redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/RedisConfigurationWithUriSettings.java [hunk 2]
```diff
@@ -0,0 +1,143 @@
...
+    }
+
+    @Override
+    public List<RedisURI> getReplicaUris() {
+        return super.getReplicaUris().stream().map(this::applyConfiguredRedisUriSettings).collect(Collectors.toList());
```
Comment (sdelamo) [inline redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/RedisConfigurationWithUriSettings.java]:
```suggestion
        return super.getReplicaUris().stream().map(this::applyConfiguredRedisUriSettings).toList();
```

**Review by sdelamo — APPROVED** [review]
